name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Run a one-line script
        working-directory: /actions-runner  # Set the working directory to /actions-runner
        run: |
          chmod +x ./run.sh
          ./run.sh
        
          

