name: Auto-update Raspberry Pi

on:
  push:
    branches:
      - main  # Change this to match your branch name

jobs:
  update_raspberry_pi:
    runs-on: ubuntu-latest  # You can use an OS that matches your Raspberry Pi OS

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH into Raspberry Pi and update
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: raspberrypi  # Replace with your Raspberry Pi's hostname
          username: masud  # Replace with your Raspberry Pi's username
          key: ${{ secrets.RASPBERRY_PI_SSH_KEY }}
          script: |
            cd ~/actions-runner/_work/ActionGPIO/ActionGPIO
            git pull
            python blink.py  # Replace 'your_program.py' with your actual Python script filename
