name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Run a one-line script
        run: |
          echo Hello raspberry!
          # Add a step to run your shell script on the Raspberry Pi
          ssh masud@raspberrypi:~/actions-runner && ./run.sh"

